### ISSUE TITLE
cannot import name 'chart_decoder'

### ISSUE THREAD

**Issue by HongyanJiao** [nikitakit/self-attentive-parser#31]
import benepar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/self-attentive-parser-acl2018/benepar/__init__.py", line 6, in <module>
    from .nltk_plugin import Parser
  File "/project/self-attentive-parser-acl2018/benepar/nltk_plugin.py", line 4, in <module>
    from .base_parser import BaseParser
  File "/project/self-attentive-parser-acl2018/benepar/base_parser.py", line 6, in <module>
    from . import chart_decoder
ImportError: cannot import name 'chart_decoder'

**Comment by nikitakit** [comment]
Installing benepar requires using either `pip install benepar` or cloning the git repo and installing (e.g. by running `pip install .` or `python setup.py`)

Directly importing a git clone of the repository won't be able to find a compiled version of the CKY chart decoder, which will result in this error message.

**Comment by minstar** [comment]
I've tried all of these methods, but still have the same problem.
Also, I have tried ```python setup.py build``` and ```python setup.py install``` but still same.
Is there any solution?

**Comment by HongyanJiao** [comment]
have you ever tried to reinstall torch==0.4.1



---Original---

**Comment by lvaleriu** [comment]
Can it work with torch==1.1.0 or 1.2.0?

**Comment by nikitakit** [comment]
@lvaleriu Pytorch 1.1.0 works; it's what I'm running now on my machines. I've heard reports that things break in 1.2.0 though, so you may want to hold off on going past 1.1.0.

**Comment by mhuang2020** [comment]
I am still receiving this error, and I have tried all of the suggested solutions. 
I am currently running on Python 3.6.9, Pip 20.0.2, and Tensorflow 2.1.0.
Everything works with no problems up to the point where I need to import Benepar, at which point I get the ImportError: cannot import name 'chart_decoder.' Please let me know if any of my system requirements are off, or if there are any possible solutions to my problem. Thank you.

**Comment by pdcoded** [comment]
This issue needs to be re-opened again
